- name: my first playbook
  hosts: localhost
  tasks:
    - name: Print message
      debug:
        msg: Hello world

    - name: Install qtile apt package
      become: true
      apt:
        name:
          - qtile
          - brightnessctl
          - pavucontrol
          - neovim
          - picom
          - dunst
          - stow
          - pip
          - git
          - curl
          - j4-dmenu-desktop
          - dmenu
          - zsh
        update_cache: yes
      register: packages

    - debug: msg="{{packages}}"

    - name: install qtile-extras
      pip:
        name: qtile-extras==0.31.0
        break_system_packages: true

    - name: symlink qtile configuration files
      file:
        src: ./.config/qtile
        dest: ~/.config/qtile
        state: link

    - name: symlink picom configuration files
      file:
        src: ./.config/picom
        dest: ~/.config/picom
        state: link

    - name: symlink dunst configuration files
      file:
        src: ./.config/dunst
        dest: ~/.config/dunst
        state: link
